### ISSUE TITLE
"filter for the files"?

### ISSUE THREAD

**Issue by hedefalk** [fs-utils/fs-readdir-recursive#7]
Seems the filter is tested only on directories in the recursive path? I read the readme and figured I could use this for my use case of getting all files called ".ensime" at any depth in a folder. Seems the filter is applied on directories but not on file. Kindof misleading text, no?

**Comment by coderhaoxin** [comment]
filter is also recursive

**Comment by hedefalk** [comment]
Well, my use case is pretty simple:

Say I want to find both `.ensime` files in this tree:
```
foo
|-- .ensime
|-- bar
|   |-- .ensime
|   `-- ignore.txt
`-- ignore.txt
```

Couldn't get it to work. If I tried to check for `file.endsWith(".ensime")` bar wasn't traversed.

**Comment by coderhaoxin** [comment]
```js
read('foo', (file) => {
  return file.endsWith(".ensime")
})
```

@hedefalk this not works?

**Comment by hedefalk** [comment]
@coderhaoxin No, doesn't seem like it. You filter both files and dirs here, right?

 https://github.com/fs-utils/fs-readdir-recursive/blob/master/index.js#L15

So it wont even traverse my folder `bar` since it doesn't end in `.ensime`, right?

Sorry, but I had to chose a entirely different solution using a cached index since I had a lot of files: https://discuss.atom.io/t/find-files-programmatically-and-fast/23521/5

**Comment by coderhaoxin** [comment]
Oh, I see! 

Maybe you can try

```js
read('your path').filter(...)
```
